{% set name = "pegasus-wms" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}-build
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pegasus-wms-{{ version }}.tar.gz
  sha256: 2d4deabeb682613709185439586cc6ea9adb9446c6f374e6ebd5e3e296a6e48c

build:
  noarch: python
  number: 0

outputs:
  - name: pegasus-wms
    script: build-pegasus-wms.sh
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.5
        - setuptools
      run:
        - flask >1.1,<1.2
        - flask-caching >1.8,<1.11
        - gitpython >1.0,<3.2
        - pamela >=1.0,<1.1
        - pegasus-wms.api <5.2
        - pegasus-wms.common <5.2
        - pegasus-wms.dax <5.2
        - pegasus-wms.worker <5.2
        - pika 1.1.0
        - python >=3.5
        - pyyaml >5.3,<5.5
        - requests >2.23,<2.26
        - sqlalchemy >1.3,<1.4
    test:
      requires:
        - pip
      imports:
        - Pegasus
      commands:
        - python -m pip check

  - name: python-pegasus-wms
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pegasus-wms", max_pin="x.x.x") }}
    test:
      imports:
        - Pegasus

about:
  home: http://pegasus.isi.edu
  dev_url: https://github.com/pegasus-isi/pegasus.git
  summary: Pegasus Workflow Management System Python API
  license: Apache-2.0
  license_file: LICENSE

extra:
  feedstock-name: pegasus-wms
  recipe-maintainers:
    - duncanmmacleod
