{% set name = "pegasus-wms" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pegasus-wms-{{ version }}.tar.gz
  sha256: 2d4deabeb682613709185439586cc6ea9adb9446c6f374e6ebd5e3e296a6e48c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=44.0.0
  run:
    - flask >1.1
    - flask-caching >1.8
    - gitpython >1.0
    - pamela >=1.0
    - pegasus-wms.api
    - pegasus-wms.common
    - pegasus-wms.dax
    - pegasus-wms.worker
    - pika >=1.1.0
    - python >=3.5
    - pyyaml >5.3
    - requests >2.23
    - sqlalchemy >1.3,<1.4

test:
  requires:
    - pip
  imports:
    - Pegasus
  commands:
    - python -m pip check

about:
  home: http://pegasus.isi.edu
  dev_url: https://github.com/pegasus-isi/pegasus.git
  summary: Pegasus Workflow Management System Python API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
